spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: access-key
      secret-key: secret-key
      oss:
        endpoint: oss-eu-central-1.aliyuncs.com
        bucket: gulimall-shengbo
      sms:
        host: "https://dfsns.market.alicloudapi.com"
        path: "/data/send_sms"
        template_id: "TPL_0001"
        appcode: "0a7c8af6495349d29f1f4e810bf4da82"
  application:
    name: gulimall-third-party


server:
  port: 30000
